stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.prod
      buildContext: .
      tag: smi-mobile:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.lappis.rocks

- name: Deploy Staging
  when:
    branch: development
  steps:
  - applyYamlConfig:
      path: ./deploy/staging/deployment-mobile.yaml

branch:
  include: [ master, development ]
notification: {}
